### PR TITLE
3.0.0 grammar and cleanup

### PR DESCRIPTION
**Pull request by nyurik**
* a few minor spelling/typo/grammar changes
* use https instead of http as a default

### CODE REVIEW

**Comment by Tinar58** [comment]
What in this

**Comment by Tinar58** [comment]
@zugaldia

**Comment by nyurik** [comment]
any update on this? even #68 is pending this...

**Comment by nyurik** [comment]
a friendly ping... is this spec maintained? thx!

**Review by mapsam — APPROVED** [review]
Hello @nyurik - thank you for the edits and apologies for the delay. Approved! 

I'll merge into the primary branch and just keep this as 3.0.0 without any bumps to the specification, as these are syntactical and copy edits.

**Pull request merged**
